#!/usr/bin/env bash

#   [ MAKE MARKDOWN TABLE of FONT INFO USING `fc-list` ]
#   ----------------------------------------------------
#
#     Generate a table of font information based off a regex used to
#     search over the Font Family category using fc-list
#
#     [[ EXAMPLE ]] :
# 
# | FONT FAMILY             | FONT STYLE        | TRUETYPE FILE                                                         |
# | ----------------------- | ----------------- | --------------------------------------------------------------------- |
# | Cousine Nerd Font Mono  | style=Bold Italic | /usr/share/fonts/truetype/cousine/CousineNerdFontMono-BoldItalic.ttf  |
# | Cousine Nerd Font Mono  | style=Bold        | /usr/share/fonts/truetype/cousine/CousineNerdFontMono-Bold.ttf        |
# | Cousine Nerd Font Mono  | style=Italic      | /usr/share/fonts/truetype/cousine/CousineNerdFontMono-Italic.ttf      |
# | Cousine Nerd Font Mono  | style=Regular     | /usr/share/fonts/truetype/cousine/CousineNerdFontMono-Regular.ttf     |
# | Cousine Nerd Font Propo | style=Bold Italic | /usr/share/fonts/truetype/cousine/CousineNerdFontPropo-BoldItalic.ttf |
# | Cousine Nerd Font Propo | style=Bold        | /usr/share/fonts/truetype/cousine/CousineNerdFontPropo-Bold.ttf       |
# | Cousine Nerd Font Propo | style=Italic      | /usr/share/fonts/truetype/cousine/CousineNerdFontPropo-Italic.ttf     |
# | Cousine Nerd Font Propo | style=Regular     | /usr/share/fonts/truetype/cousine/CousineNerdFontPropo-Regular.ttf    |
# | Cousine Nerd Font       | style=Bold Italic | /usr/share/fonts/truetype/cousine/CousineNerdFont-BoldItalic.ttf      |
# | Cousine Nerd Font       | style=Bold        | /usr/share/fonts/truetype/cousine/CousineNerdFont-Bold.ttf            |
# | Cousine Nerd Font       | style=Italic      | /usr/share/fonts/truetype/cousine/CousineNerdFont-Italic.ttf          |
# | Cousine Nerd Font       | style=Regular     | /usr/share/fonts/truetype/cousine/CousineNerdFont-Regular.ttf         |
#


#  If no argument is given to use as the regex
#. then set a default regex to search for Cousine
if [[ "x$1" == "x" ]]; then
        regex='[Cc]ousine'
else
        regex="$1"
fi

FONT_FAMILY_CSV="$(
        printf '%s\n%s\n' \
                "$(echo FONT\ FAMILY:FONT\ STYLE:TRUETYPE\ FILE)" \
                "$(
                        fc-list : name family style file |
                                awk -F: '{ printf("%s,%s,%s\n", $2, $3, $1 )}' |
                                sed -E 's/ ?, ?/,/' |
                                grep -i "$regex" |
                                tr , ':' |
                                sed 's/^[[:space:]]*//' |
                                sort
                )" | tr ':' ','
)"

echo "$FONT_FAMILY_CSV" | csvlook || {
        echo "Failed to generate markdown table with $(csvlook), here's the CSV itself:"
        echo "$FONT_FAMILY_CSV"
}
